CREATE TABLE [dbo].[class]
(
	[Id] INT NOT NULL PRIMARY KEY,
  [name] VARCHAR(100),
  type VARCHAR(255),
  alignment VARCHAR(255),
  hit_die VARCHAR(255),
  class_skills TEXT,
  skill_points VARCHAR(255),
  skill_points_ability VARCHAR(255),
  spell_stat VARCHAR(255),
  proficiencies TEXT,
  spell_type VARCHAR(255),
  epic_feat_base_level VARCHAR(255),
  epic_feat_interval VARCHAR(255),
  epic_feat_list TEXT,
  epic_full_text TEXT,
  req_race VARCHAR(255),
  req_weapon_proficiency VARCHAR(255),
  req_base_attack_bonus VARCHAR(255),
  req_skill VARCHAR(255),
  req_feat VARCHAR(255),
  req_spells VARCHAR(255),
  req_languages VARCHAR(255),
  req_psionics VARCHAR(255),
  req_epic_feat VARCHAR(255),
  req_special VARCHAR(255),
  spell_list_1 TEXT,
  spell_list_2 VARCHAR(255),
  spell_list_3 VARCHAR(255),
  spell_list_4 VARCHAR(255),
  spell_list_5 VARCHAR(255),
  full_text TEXT,
  reference VARCHAR(255)
)
