CREATE TABLE [dbo].[monster]
(
	[Id] INT NOT NULL PRIMARY KEY,
  family VARCHAR(255),
  [name] VARCHAR(100),
  altname VARCHAR(255),
  [size] VARCHAR(255),
  type VARCHAR(255),
  descriptor VARCHAR(255),
  hit_dice VARCHAR(255),
  initiative VARCHAR(255),
  speed VARCHAR(255),
  armor_class VARCHAR(255),
  base_attack VARCHAR(255),
  grapple VARCHAR(255),
  attack VARCHAR(255),
  full_attack TEXT,
  [space] VARCHAR(255),
  reach VARCHAR(255),
  special_attacks VARCHAR(255),
  special_qualities TEXT,
  saves VARCHAR(255),
  abilities VARCHAR(255),
  skills TEXT,
  bonus_feats VARCHAR(255),
  feats TEXT,
  epic_feats TEXT,
  environment VARCHAR(255),
  organization TEXT,
  challenge_rating VARCHAR(255),
  treasure VARCHAR(255),
  alignment VARCHAR(255),
  advancement VARCHAR(255),
  level_adjustment VARCHAR(255),
  special_abilities TEXT,
  stat_block TEXT,
  full_text TEXT,
  reference VARCHAR(255)
)
