CREATE TABLE [dbo].[spell]
(
	[Id] INT NOT NULL PRIMARY KEY,
  [name] VARCHAR(100),
  altname VARCHAR(255),
  school VARCHAR(255),
  subschool VARCHAR(255),
  descriptor VARCHAR(255),
  spellcraft_dc VARCHAR(255),
  [level] VARCHAR(255),
  components TEXT,
  casting_time VARCHAR(255),
  range VARCHAR(255),
  target VARCHAR(255),
  area VARCHAR(255),
  effect VARCHAR(255),
  duration VARCHAR(255),
  saving_throw VARCHAR(255),
  spell_resistance VARCHAR(255),
  short_description VARCHAR(255),
  to_develop TEXT,
  material_components TEXT,
  arcane_material_components VARCHAR(255),
  focus TEXT,
  description TEXT,
  xp_cost TEXT,
  arcane_focus VARCHAR(255),
  wizard_focus VARCHAR(255),
  verbal_components VARCHAR(255),
  sorcerer_focus VARCHAR(255),
  bard_focus VARCHAR(255),
  cleric_focus VARCHAR(255),
  druid_focus VARCHAR(255),
  full_text TEXT,
  reference VARCHAR(255)
)
